image: python

stages:
  - test
  - build
  - release

before_script:
  - python -V
  - pip install pip --upgrade
  - pip install tox

python37:
  image: python:3.7
  stage: test
  script: tox -e py37

linters:
  image: python:3.7
  stage: test
  script: tox -e linters

pre-commit:
  image: python:3.7
  stage: test
  script: tox -e pre-commit

build:
  image: python:3.7
  stage: build
  script:
    - git remote set-url origin https://oauth2:$GIT_CI_PASS@gitlab.com/roey.asher/uni.git
    - git config --global user.email 'roey.asher@nielsen.com'
    - git config --global user.name 'roey.asher'
    - pip install bump2version
    - bump2version build
    - git push origin development
  only:
    - development

release:
  image: python:3.7
  stage: release
  script:
    - git remote set-url origin https://oauth2:$GIT_CI_PASS@gitlab.com/roey.asher/uni.git
    - git config --global user.email 'roey.asher@nielsen.com'
    - git config --global user.name 'roey.asher'
    - pip install bump2version
    - bump2version release
    - git push origin master
  only:
    - master

#build:
#  stage: build
#  script: tox -e build
#  artifacts:
#    paths:
#    - dist/
#    expire_in: 1 month


#release:
#  stage: release
#  script: tox -e build
#  artifacts:
#    paths:
#    - dist
#  only:
#  - tags
