image: python

stages:
  - test
  - build
  - release

before_script:
  - echo $GIT_CI_PASS
  - python -V
  - pip install pip --upgrade
  - pip install tox

python37:
  image: python:3.7
  stage: test
  script: tox -e py37

linters:
  image: python:3.7
  stage: test
  script: tox -e linters

pre-commit:
  image: python:3.7
  stage: test
  script: tox -e pre-commit

build:
  image: python:3.7
  stage: build
  script: tox -e build
  only:
    - development

release:
  image: python:3.7
  stage: release
  script: tox -e release
  only:
    - master

#build:
#  stage: build
#  script: tox -e build
#  artifacts:
#    paths:
#    - dist/
#    expire_in: 1 month


#release:
#  stage: release
#  script: tox -e build
#  artifacts:
#    paths:
#    - dist
#  only:
#  - tags
