image: python

stages:
  - test
  - build
  - release

before_script:
  - python -V
  - pip install pip --upgrade
  - pip install tox

python37:
  image: python:3.7
  stage: test
  script: tox -e py37

linters:
  image: python:3.7
  stage: test
  script: tox -e linters

pre-commit:
  image: python:3.7
  stage: test
  script: tox -e pre-commit

build:
  stage: build
  script: tox -e build
  artifacts:
    paths:
    - dist/
    expire_in: 1 month
    onl

#release:
#  stage: release
#  script: tox -e build
#  artifacts:
#    paths:
#    - dist
#  only:
#  - tags
