image: python

stages:
  - test
#  - build
  - version
#  - release

before_script:
  - git remote set-url origin https://roey.asher:${CI_PUSH_TOKEN}@gitlab.com/uni.git
  - git config --global user.email 'roey.asher@nielsen.com'
  - git config --global user.name 'roey.asher'
  - python -V
  - pip install pip --upgrade
  - pip install tox

python37:
  image: python:3.7
  stage: test
  script: tox -e py37

linters:
  image: python:3.7
  stage: test
  script: tox -e linters

pre-commit:
  image: python:3.7
  stage: test
  script: tox -e pre-commit

version:
  stage: version
  script: tox -e bumpversion
  only:
  - master

#build:
#  stage: build
#  script: tox -e build
#  artifacts:
#    paths:
#    - dist/
#    expire_in: 1 month


#release:
#  stage: release
#  script: tox -e build
#  artifacts:
#    paths:
#    - dist
#  only:
#  - tags
