image: python

stages:
  - test
#  - build
  - version
#  - release

before_script:
  - python -V
  - pip install pip --upgrade
  - pip install tox

python37:
  image: python:3.7
  stage: test
  script: tox -e py37

linters:
  image: python:3.7
  stage: test
  script: tox -e linters

pre-commit:
  image: python:3.7
  stage: test
  script: tox -e pre-commit

version:
  image: python:3.7
  stage: version
  script:
    - pip install bump2version
    - git remote set-url origin https://$GIT_CI_USER:$GIT_CI_PASS@gitlab.com/uni.git
    - git config --global user.email 'roey.asher@nielsen.com'
    - git config --global user.name 'roey.asher'
    - git checkout -B bumpversion
    - bump2version patch setup.py
    - git commit -m '[skip ci] commit from ci user'
    - git push origin branch
  only:
    - master

#build:
#  stage: build
#  script: tox -e build
#  artifacts:
#    paths:
#    - dist/
#    expire_in: 1 month


#release:
#  stage: release
#  script: tox -e build
#  artifacts:
#    paths:
#    - dist
#  only:
#  - tags
