image: python

stages:
  - test
  - build
  - release

before_script:
  - echo $GIT_CI_PASS
  - python -V
  - pip install pip --upgrade
  - pip install tox

python37:
  image: python:3.7
  stage: test
  script: tox -e py37

linters:
  image: python:3.7
  stage: test
  script: tox -e linters

pre-commit:
  image: python:3.7
  stage: test
  script: tox -e pre-commit

build:
  image: python:3.7
  stage: build
  before_script:
    - pip install bump2version
  script:
    - git remote set-url origin https://oauth2:${GIT_CI_PASS}@gitlab.com/roey.asher/uni.git
    - git config --global user.email 'roey.asher@nielsen.com'
    - git config --global user.name 'gitbot'
    - git clone -b ${CI_COMMIT_BRANCH} https://oauth2:${GIT_CI_PASS}@gitlab.com/roey.asher/uni.git
    - cd ${CI_PROJECT_NAME}
    - bump2version build
    - git push origin ${CI_COMMIT_BRANCH}
  only:
    - development

release:
  image: python:3.7
  stage: release
  before_script:
    - pip install bump2version
  script:
    - git remote set-url origin https://oauth2:${GIT_CI_PASS}@gitlab.com/roey.asher/uni.git
    - git config --global user.email 'roey.asher@nielsen.com'
    - git config --global user.name 'gitbot'
    - git clone -b ${CI_COMMIT_BRANCH} https://oauth2:${GIT_CI_PASS}@gitlab.com/roey.asher/uni.git
    - cd ${CI_PROJECT_NAME}
    - bump2version release
    - git push origin ${CI_COMMIT_BRANCH}
  only:
    - master

#build:
#  stage: build
#  script: tox -e build
#  artifacts:
#    paths:
#    - dist/
#    expire_in: 1 month


#release:
#  stage: release
#  script: tox -e build
#  artifacts:
#    paths:
#    - dist
#  only:
#  - tags
