name: uni
channels:
  - defaults
dependencies:
  - python=3.7
  - pandas
  - numpy
  - pyarrow
  - scikit-learn
  - jupyter
  - pip
  - pip:
      - mlflow
      - prefect[dev]
      - apache-airflow
      - pendulum==1.4.4
      - pyspark
      - tox